### ISSUE TITLE
Keep Myth Syntax

### ISSUE THREAD

**Issue by shawnrice** [toreholmberg/atom-myth#1]
I hadn't heard of Myth before seeing this package, and now I'm hooked.

I might be missing something, but when I invoke Myth, then it also gets rid of all of my Myth syntax, which seems great for a final product, but if I'm testing/tweaking something, then I'll find myself constantly invoking Myth, Saving, then Undoing.

I realize I might have the wrong workflow, but is there something akin to compiling the CSS with Myth, so that it would generate another file with the CSS so that we don't lose that work?

**Comment by toreholmberg** [comment]
A basic version of this is implemented in version 0.3.0 (d671117d2f01ea5235d61fb12e8b92e5c835e614). Content is now compiled into a new file suffixed with `output`.

```
css/styles.css => css/styles.output.css
```

Improving this for more flexible naming and output directories is on the roadmap.
